# Generated by Django 3.2.6 on 2021-08-10 19:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=300, verbose_name=django.contrib.auth.models.User)),
                ('ln', models.CharField(max_length=300, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(default='someone@mail.com', max_length=500)),
                ('password', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='user.png', upload_to='userimage')),
                ('created', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
